apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-test-64-h100-8n
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: ghcr.io/coreweave/nccl-tests:12.9.1-devel-ubuntu22.04-nccl2.28.3-1-8b67957
              name: nccl
              env:
                - name: OMPI_ALLOW_RUN_AS_ROOT
                  value: "1"
                - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
                  value: "1"
              # Uncomment to be able to exec in to launcher pod for interactive testing
              # command: [ 'sleep', '86400' ]
              command: ["/bin/bash", "-c"]
              # Can also try setting '-x NCCL_ALGO=NVLSTREE'
              args: [
                  "mpirun \
                  -np 64 \
                  -bind-to none \
                  -x LD_LIBRARY_PATH \
                  -x NCCL_SOCKET_IFNAME=eth0 \
                  -x NCCL_IB_HCA=ibp \
                  -x UCX_NET_DEVICES=ibp0:1,ibp1:1,ibp2:1,ibp3:1,ibp4:1,ibp5:1,ibp6:1,ibp7:1 \
                  -x SHARP_COLL_ENABLE_PCI_RELAXED_ORDERING=1 \
                  -x NCCL_COLLNET_ENABLE=0 \
                  /opt/nccl_tests/build/all_reduce_perf -b 512M -e 8G -f 2 -g 1 #-n 200 #-w 2 -n 20
                  ",
                ]
              resources:
                requests:
                  cpu: 2
                  memory: 128Mi
    Worker:
      replicas: 8
      template:
        labels:
          metadata.coreweave.cloud/job: nccl-test
        spec:
          containers:
            - image: ghcr.io/coreweave/nccl-tests:12.9.1-devel-ubuntu22.04-nccl2.28.3-1-8b67957
              name: nccl
              resources:
                requests:
                  cpu: 110
                  memory: 960Gi
                  nvidia.com/gpu: 8
                  rdma/ib: 1
                limits:
                  memory: 960Gi
                  nvidia.com/gpu: 8
                  rdma/ib: 1
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.coreweave.cloud/type
                        operator: In
                        values:
                          - gd-8xh100ib-i128
          volumes:
            - emptyDir:
                medium: Memory
              name: dshm
