apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-test-64-a40
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
          spec:
            containers:
            - image: ghcr.io/coreweave/nccl-tests:11.7.1-devel-ubuntu20.04-nccl2.14.3-1-45d6ec9
              name: nccl
              env:
              - name: OMPI_ALLOW_RUN_AS_ROOT
                value: "1"
              - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
                value: "1"
              # Uncomment to be able to exec in to launcher pod for interactive testing
              # command: ['sleep', '86400']
              command: ["/bin/bash", "-c"]
              args: ["mpirun \
                    -np 64 \
                    -x LD_LIBRARY_PATH \
                    -x NCCL_SOCKET_IFNAME=eth0 \
                    -x NCCL_IB_HCA=ibp \
                    -x NCCL_DEBUG=INFO \
                    -x NCCL_DEBUG_SUBSYS=INIT \
                    /opt/nccl_tests/build/all_reduce_perf -b 4 -e 2G -f 2 -g 1 -w 50 -n 50
                    "]

              resources:
                requests:
                  cpu: 2
                  memory: 128Mi
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/region
                        operator: In
                        values:
                        - LAS1

            schedulerName: prioritize-image-locality
            enableServiceLinks: false
            automountServiceAccountToken: false
    Worker:
      replicas: 8
      template:
        spec:
          containers:
          - image: ghcr.io/coreweave/nccl-tests:11.7.1-devel-ubuntu20.04-nccl2.14.3-1-45d6ec9
            name: nccl
            resources:
              requests:
                cpu: 90
                memory: 400Gi
                nvidia.com/gpu: 8
              limits:
                nvidia.com/gpu: 8
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: gpu.nvidia.com/model
                    operator: In
                    values:
                    - A40
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                    - LAS1

          volumes:
            - emptyDir:
                medium: Memory
              name: dshm
          enableServiceLinks: false
          automountServiceAccountToken: false
