on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .github/workflows/ubuntu-24.yml
      - .github/workflows/build.yml

jobs:
  cu129:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile
      base-image: nvidia/cuda
      base-tag: 12.9.1-devel-ubuntu24.04
      cuda-version: "12.9.1"
      nccl-version: 2.27.7-1
      cuda-samples-version: "12.5"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu24.04-cuda12"
