on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.ubuntu22
      - .github/workflows/ubuntu-22.yml
      - .github/workflows/build.yml

jobs:
  cu130:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 13.0.0-devel-ubuntu22.04
      cuda-version: "13.0.0"
      nccl-version: 2.27.7-1
      cuda-samples-version: "13.0"
      hpcx-distribution: "hpcx-v2.24-gcc-doca_ofed-ubuntu22.04-cuda13"
