on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.ubuntu22
      - .github/workflows/ubuntu-22.yml
      - .github/workflows/build.yml

jobs:
  cu120:
    uses: ./.github/workflows/build.yml
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.0.1-cudnn8-devel-ubuntu22.04
      cuda-version-minor: "12.0.1"
      cuda-version-major: "12.0"
      nccl-version: 2.18.5-1
      cuda-samples-version: "12.0"
      hpcx-distribution: "hpcx-v2.18-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu121:
    uses: ./.github/workflows/build.yml
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.1.1-cudnn8-devel-ubuntu22.04
      cuda-version-minor: "12.1.1"
      cuda-version-major: "12.1"
      nccl-version: 2.18.3-1
      cuda-samples-version: "12.1"
      hpcx-distribution: "hpcx-v2.18-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu122:
    uses: ./.github/workflows/build.yml
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.2.2-cudnn8-devel-ubuntu22.04
      cuda-version-minor: "12.2.2"
      cuda-version-major: "12.2"
      nccl-version: 2.19.3-1
      cuda-samples-version: "12.2"
      hpcx-distribution: "hpcx-v2.18-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu123:
    uses: ./.github/workflows/build.yml
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.3.2-cudnn9-devel-ubuntu22.04
      cuda-version-minor: "12.3.2"
      cuda-version-major: "12.3"
      nccl-version: 2.20.3-1
      cuda-samples-version: "12.3"
      hpcx-distribution: "hpcx-v2.18-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"
