on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.ubuntu22
      - .github/workflows/ubuntu-22.yml
      - .github/workflows/build.yml

jobs:
  cu120:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_DOPPLER_CONFIG: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_CONFIG }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.0.1-cudnn8-devel-ubuntu22.04
      cuda-version-minor: "12.0.1"
      cuda-version-major: "12.0"
      nccl-version: 2.18.5-1
      cuda-samples-version: "12.0"
      hpcx-distribution: "hpcx-v2.20-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu122:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_DOPPLER_CONFIG: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_CONFIG }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.2.2-cudnn8-devel-ubuntu22.04
      cuda-version-minor: "12.2.2"
      cuda-version-major: "12.2"
      nccl-version: 2.23.4-1
      cuda-samples-version: "12.2"
      hpcx-distribution: "hpcx-v2.20-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu124:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_DOPPLER_CONFIG: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_CONFIG }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.4.1-cudnn-devel-ubuntu22.04
      cuda-version-minor: "12.4.1"
      cuda-version-major: "12.4"
      nccl-version: 2.23.4-1
      cuda-samples-version: "12.4"
      hpcx-distribution: "hpcx-v2.20-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"

  cu126:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_DOPPLER_CONFIG: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_CONFIG }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.6.1-cudnn-devel-ubuntu22.04
      cuda-version-minor: "12.6.1"
      cuda-version-major: "12.6"
      nccl-version: 2.23.4-1
      cuda-samples-version: "12.5"
      hpcx-distribution: "hpcx-v2.20-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64"
