on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.ubuntu22
      - .github/workflows/ubuntu-22.yml
      - .github/workflows/build.yml

jobs:
  cu122:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.2.2-devel-ubuntu22.04
      cuda-version: "12.2.2"
      nccl-version: 2.26.5-1
      cuda-samples-version: "12.2"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu22.04-cuda12"

  cu124:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.4.1-devel-ubuntu22.04
      cuda-version: "12.4.1"
      nccl-version: 2.26.5-1
      cuda-samples-version: "12.4"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu22.04-cuda12"

  cu126:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.6.3-devel-ubuntu22.04
      cuda-version: "12.6.3"
      nccl-version: 2.26.5-1
      cuda-samples-version: "12.5"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu22.04-cuda12"

  cu128:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.8.1-devel-ubuntu22.04
      cuda-version: "12.8.1"
      nccl-version: 2.26.5-1
      cuda-samples-version: "12.5"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu22.04-cuda12"

  cu129:
    uses: ./.github/workflows/build.yml
    secrets:
      ORG_BUILDKIT_CLIENT_TOKEN: ${{ secrets.ORG_BUILDKIT_CLIENT_TOKEN }}
      BUILDKIT_CONSUMER_DOPPLER_PROJECT: ${{ secrets.BUILDKIT_CONSUMER_DOPPLER_PROJECT }}
      BUILDKIT_CONSUMER_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ENDPOINT }}
      BUILDKIT_CONSUMER_AMD64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_AMD64_ENDPOINT }}
      BUILDKIT_CONSUMER_ARM64_ENDPOINT: ${{ secrets.BUILDKIT_CONSUMER_ARM64_ENDPOINT }}
    with:
      folder: .
      dockerfile: Dockerfile.ubuntu22
      base-image: nvidia/cuda
      base-tag: 12.9.0-devel-ubuntu22.04
      cuda-version: "12.9.0"
      nccl-version: 2.26.5-1
      cuda-samples-version: "12.5"
      hpcx-distribution: "hpcx-v2.23-gcc-doca_ofed-ubuntu22.04-cuda12"
